export const colorTokens = {
  background: "#F8FAFC",
  surface: "#FFFFFF",
  surfaceSecondary: "#F1F5F9",
  surfaceMuted: "#FAFBFC",
  border: "#CBD5E1",
  borderSubtle: "#E2E8F0",
  textPrimary: "#0F172A",
  textSecondary: "#1E293B",
  textMuted: "#475569",
  textSubtle: "#64748B",
  textInverse: "#FFFFFF",
  brand: "#2563EB",
  brandLight: "#3B82F6",
  brandSoft: "#EFF6FF",
  brandBorder: "#BFDBFE",
  success: "#16A34A",
  successText: "#166534",
  successSoft: "#F0FDF4",
  successBorder: "#BBF7D0",
  warning: "#F59E0B",
  warningText: "#92400E",
  warningSoft: "#FFFBEB",
  warningBorder: "#FDE68A",
  danger: "#EF4444",
  dangerText: "#B91C1C",
  dangerSoft: "#FEF2F2",
  dangerBorder: "#FECACA",
  shadow: "rgba(15, 23, 42, 0.08)",
  shadowStrong: "rgba(15, 23, 42, 0.14)",
  placeholderText: "#94A3B8",
  inputBackground: "#F1F5F9",
  inputBackgroundFocused: "#FFFFFF",
  inputBackgroundError: "#FEF2F2",
  inputBorder: "#E2E8F0",
  inputBorderFocused: "#3B82F6",
  inputBorderError: "#FCA5A5",
  inputFocusRing: "rgba(59, 130, 246, 0.18)",
  rippleNeutral: "rgba(15, 23, 42, 0.06)",
  ripplePrimary: "rgba(255, 255, 255, 0.18)",
  rippleDanger: "rgba(239, 68, 68, 0.18)",
} as const;

export const spacingTokens = {
  screenX: 16,
  sectionGap: 16,
  cardGap: 8,
} as const;

export const radiusTokens = {
  card: 16,
  control: 12,
  pill: 999,
} as const;

export const webSpacingTokens = {
  xs: "4px",
  sm: "8px",
  md: "12px",
  lg: "16px",
  xl: "20px",
  "2xl": "24px",
  "3xl": "32px",
  "4xl": "40px",
  "5xl": "48px",
} as const;

export const webRadiusTokens = {
  sm: "6px",
  md: "8px",
  lg: "10px",
  xl: "12px",
  tabShell: "var(--dg-radius-md)",
  tabShellPad: "2px",
  tabInner: "calc(var(--dg-tab-shell-radius) - var(--dg-tab-shell-pad))",
} as const;

export const typographyTokens = {
  fontSize: {
    pageTitle: "28px",
    sectionTitle: "24px",
    cardTitle: "20px",
    heading: "18px",
    title: "16px",
    body: "15px",
    bodySm: "14px",
    label: "13px",
    caption: "12px",
    footnote: "11px",
    badge: "10px",
    micro: "9px",
  },
  lineHeight: {
    tight: "1.1",
    normal: "1.4",
    loose: "1.6",
  },
} as const;

export const mobileTypographyTokens = {
  fontFamily: {
    base: "DMSans_400Regular",
    regular: "DMSans_400Regular",
    medium: "DMSans_500Medium",
    semibold: "DMSans_600SemiBold",
    bold: "DMSans_700Bold",
  },
  fontWeight: {
    regular: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
  },
  text: {
    screenTitle: {
      fontFamily: "DMSans_700Bold",
      fontSize: 22,
      lineHeight: 28,
      fontWeight: "700",
    },
    heroMetric: {
      fontFamily: "DMSans_700Bold",
      fontSize: 24,
      lineHeight: 30,
      fontWeight: "700",
    },
    sectionTitle: {
      fontFamily: "DMSans_700Bold",
      fontSize: 16,
      lineHeight: 22,
      fontWeight: "700",
    },
    cardTitle: {
      fontFamily: "DMSans_600SemiBold",
      fontSize: 16,
      lineHeight: 22,
      fontWeight: "600",
    },
    rowTitle: {
      fontFamily: "DMSans_600SemiBold",
      fontSize: 15,
      lineHeight: 21,
      fontWeight: "600",
    },
    body: {
      fontFamily: "DMSans_400Regular",
      fontSize: 14,
      lineHeight: 21,
      fontWeight: "400",
    },
    bodyStrong: {
      fontFamily: "DMSans_600SemiBold",
      fontSize: 14,
      lineHeight: 21,
      fontWeight: "600",
    },
    meta: {
      fontFamily: "DMSans_400Regular",
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "400",
    },
    label: {
      fontFamily: "DMSans_600SemiBold",
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "600",
    },
    caption: {
      fontFamily: "DMSans_400Regular",
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "400",
    },
    badge: {
      fontFamily: "DMSans_700Bold",
      fontSize: 11,
      lineHeight: 14,
      fontWeight: "700",
    },
    micro: {
      fontFamily: "DMSans_600SemiBold",
      fontSize: 10,
      lineHeight: 12,
      fontWeight: "600",
    },
  },
} as const;

export const shadowTokens = {
  raised: "0 1px 4px rgba(0, 0, 0, 0.06)",
  float: "0 4px 16px rgba(0, 0, 0, 0.10)",
  menu: "0 8px 24px rgba(0, 0, 0, 0.10), 0 2px 6px rgba(0, 0, 0, 0.06)",
  modal: "0 12px 48px rgba(0, 0, 0, 0.18)",
  panel: "-8px 0 40px rgba(0, 0, 0, 0.14)",
  drag: "0 8px 24px rgba(0, 0, 0, 0.12), 0 2px 6px rgba(0, 0, 0, 0.06)",
  tooltip: "0 0 18px rgba(15, 23, 42, 0.14), 0 0 36px rgba(15, 23, 42, 0.1)",
} as const;

export const webLayoutTokens = {
  headerHeight: "56px",
  toolbarHeight: "38px",
  gridNameColumn: "220px",
  gridCellHeight: "52px",
  gridColumnMin: "72px",
} as const;

export const webResponsiveTokens = {
  tablet: {
    gridNameColumn: "180px",
    gridColumnMin: "64px",
  },
  smallDesktop: {
    pageTitle: "24px",
    sectionTitle: "22px",
  },
  mobile: {
    toolbarHeight: "var(--dg-btn-h-lg)",
    pageTitle: "22px",
    sectionTitle: "20px",
    cardTitle: "18px",
    heading: "16px",
    title: "15px",
    badge: "11px",
    micro: "10px",
    gridNameColumn: "160px",
  },
} as const;

export const buttonTokens = {
  radius: webRadiusTokens.sm,
  height: "38px",
  heightSm: "34px",
  heightXs: "30px",
  heightLg: "44px",
  paddingX: "16px",
  paddingXSm: "14px",
  paddingXXs: "10px",
  gap: "8px",
  iconSize: "14px",
} as const;

export const motionTokens = {
  fast: "150ms",
  standard: "200ms",
} as const;

export const overlayTokens = {
  background: "rgba(10, 20, 40, 0.45)",
  blur: "0px",
} as const;

export const stateEffectTokens = {
  focusRing: "rgba(59, 130, 246, 0.15)",
  dangerRing: "rgba(239, 68, 68, 0.12)",
  lockedBackground: "rgba(37, 99, 235, 0.08)",
  onDarkMuted: "rgba(255, 255, 255, 0.5)",
  onDarkSubtle: "rgba(255, 255, 255, 0.6)",
  onDarkSecondary: "rgba(255, 255, 255, 0.75)",
  onDarkDescription: "rgba(255, 255, 255, 0.82)",
  onDarkControl: "rgba(255, 255, 255, 0.18)",
  onDarkControlHover: "rgba(255, 255, 255, 0.35)",
  onDarkControlBorder: "rgba(255, 255, 255, 0.28)",
} as const;

export const toastTokens = {
  successBackground: colorTokens.success,
  successBorder: "#166534",
  errorBackground: "#DC2626",
  errorBorder: "#B91C1C",
  infoBackground: "#1D4ED8",
  infoBorder: "#1E3A8A",
  warningBackground: "#D97706",
  warningBorder: "#92400E",
} as const;

export const shadcnTokens = {
  background: "oklch(1 0 0)",
  foreground: "oklch(0.145 0 0)",
  card: "oklch(1 0 0)",
  cardForeground: "oklch(0.145 0 0)",
  popover: "oklch(1 0 0)",
  popoverForeground: "oklch(0.145 0 0)",
  primary: colorTokens.brand,
  primaryForeground: colorTokens.textInverse,
  secondary: "oklch(0.97 0 0)",
  secondaryForeground: "oklch(0.205 0 0)",
  muted: "oklch(0.97 0 0)",
  mutedForeground: "oklch(0.556 0 0)",
  accent: "oklch(0.97 0 0)",
  accentForeground: "oklch(0.205 0 0)",
  destructive: "oklch(0.577 0.245 27.325)",
  border: "oklch(0.922 0 0)",
  input: "oklch(0.922 0 0)",
  ring: colorTokens.brandLight,
  chart1: "oklch(0.87 0 0)",
  chart2: "oklch(0.556 0 0)",
  chart3: "oklch(0.439 0 0)",
  chart4: "oklch(0.371 0 0)",
  chart5: "oklch(0.269 0 0)",
  radius: "0.625rem",
  sidebar: "oklch(0.985 0 0)",
  sidebarForeground: "oklch(0.145 0 0)",
  sidebarPrimary: colorTokens.brand,
  sidebarPrimaryForeground: colorTokens.textInverse,
  sidebarAccent: colorTokens.brandSoft,
  sidebarAccentForeground: colorTokens.brand,
  sidebarBorder: "oklch(0.922 0 0)",
  sidebarRing: colorTokens.brandLight,
} as const;

export const webThemeTokens = {
  font: {
    "--font-sans": "var(--font-dm-sans), 'DM Sans', system-ui, sans-serif",
    "--font-mono": "var(--font-dm-mono), 'DM Mono', monospace",
  },
  colors: {
    "--color-bg": "var(--dg-color-bg)",
    "--color-surface": "var(--dg-color-surface)",
    "--color-bg-secondary": "var(--dg-color-bg-secondary)",
    "--color-row-alt": "var(--dg-color-row-alt)",
    "--color-row-hover": "var(--dg-color-row-hover)",
    "--color-border": "var(--dg-color-border)",
    "--color-border-light": "var(--dg-color-border-light)",
    "--color-border-focus": "var(--dg-color-border-focus)",
    "--color-text-primary": "var(--dg-color-text-primary)",
    "--color-text-secondary": "var(--dg-color-text-secondary)",
    "--color-text-muted": "var(--dg-color-text-muted)",
    "--color-text-subtle": "var(--dg-color-text-subtle)",
    "--color-text-faint": "var(--dg-color-text-faint)",
    "--color-text-inverse": "var(--dg-color-text-inverse)",
    "--color-brand": "var(--dg-color-brand)",
    "--color-brand-light": "var(--dg-color-brand-light)",
    "--color-brand-bg": "var(--dg-color-brand-bg)",
    "--color-brand-border": "var(--dg-color-brand-border)",
    "--color-primary": "var(--dg-color-primary)",
    "--color-link": "var(--dg-color-link)",
    "--color-accent-text": "var(--dg-color-accent-text)",
    "--color-control-primary": "var(--dg-color-control-primary)",
    "--color-control-primary-hover": "var(--dg-color-control-primary-hover)",
    "--color-control-primary-text": "var(--dg-color-control-primary-text)",
    "--color-control-active-bg": "var(--dg-color-control-active-bg)",
    "--color-control-active-border": "var(--dg-color-control-active-border)",
    "--color-control-active-text": "var(--dg-color-control-active-text)",
    "--color-control-active-hover": "var(--dg-color-control-active-hover)",
    "--color-success": "var(--dg-color-success)",
    "--color-success-bg": "var(--dg-color-success-bg)",
    "--color-success-text": "var(--dg-color-success-text)",
    "--color-success-border": "var(--dg-color-success-border)",
    "--color-warning": "var(--dg-color-warning)",
    "--color-warning-bg": "var(--dg-color-warning-bg)",
    "--color-warning-text": "var(--dg-color-warning-text)",
    "--color-warning-border": "var(--dg-color-warning-border)",
    "--color-danger": "var(--dg-color-danger)",
    "--color-danger-bg": "var(--dg-color-danger-bg)",
    "--color-danger-text": "var(--dg-color-danger-text)",
    "--color-danger-border": "var(--dg-color-danger-border)",
    "--color-danger-dark": "var(--dg-color-danger-dark)",
    "--color-info": "var(--dg-color-info)",
    "--color-info-bg": "var(--dg-color-info-bg)",
    "--color-info-text": "var(--dg-color-info-text)",
    "--color-info-border": "var(--dg-color-info-border)",
    "--color-dark": "var(--dg-color-dark)",
    "--color-dark-elevated": "var(--dg-color-dark-elevated)",
    "--color-today-bg": "var(--dg-color-today-bg)",
    "--color-today-text": "var(--dg-color-today-text)",
    "--color-today-border": "var(--dg-color-today-border)",
  },
} as const;

export function borderColorFromText(textHex: string, opacity = 0.35): string {
  const trimmed = textHex.trim();
  const normalized = /^#[0-9a-f]{6}$/i.test(trimmed)
    ? trimmed
    : /^#[0-9a-f]{3}$/i.test(trimmed)
      ? `#${trimmed[1]}${trimmed[1]}${trimmed[2]}${trimmed[2]}${trimmed[3]}${trimmed[3]}`
      : null;

  if (!normalized) {
    return colorTokens.border;
  }

  const r = Number.parseInt(normalized.slice(1, 3), 16);
  const g = Number.parseInt(normalized.slice(3, 5), 16);
  const b = Number.parseInt(normalized.slice(5, 7), 16);

  return `rgba(${r},${g},${b},${opacity})`;
}

export const mobileNavigationTheme = {
  dark: false,
  colors: {
    primary: colorTokens.brand,
    background: colorTokens.background,
    card: colorTokens.surface,
    text: colorTokens.textPrimary,
    border: colorTokens.borderSubtle,
    notification: colorTokens.danger,
  },
  fonts: {
    regular: {
      fontFamily: "DMSans_400Regular",
      fontWeight: "400",
    },
    medium: {
      fontFamily: "DMSans_500Medium",
      fontWeight: "500",
    },
    bold: {
      fontFamily: "DMSans_600SemiBold",
      fontWeight: "600",
    },
    heavy: {
      fontFamily: "DMSans_700Bold",
      fontWeight: "700",
    },
  },
} as const;

export function createWebCssVariables(): Record<string, string> {
  return {
    "--dg-color-bg": colorTokens.background,
    "--dg-color-surface": colorTokens.surface,
    "--dg-color-bg-secondary": colorTokens.surfaceSecondary,
    "--dg-color-row-alt": colorTokens.surfaceMuted,
    "--dg-color-row-hover": colorTokens.surfaceSecondary,
    "--dg-color-border": colorTokens.border,
    "--dg-color-border-light": colorTokens.borderSubtle,
    "--dg-color-border-focus": colorTokens.brandLight,
    "--dg-color-text-primary": colorTokens.textPrimary,
    "--dg-color-text-secondary": colorTokens.textSecondary,
    "--dg-color-text-muted": colorTokens.textMuted,
    "--dg-color-text-subtle": colorTokens.textSubtle,
    "--dg-color-text-faint": "#718096",
    "--dg-color-text-inverse": colorTokens.textInverse,
    "--dg-color-brand": colorTokens.brand,
    "--dg-color-brand-light": colorTokens.brandLight,
    "--dg-color-brand-bg": colorTokens.brandSoft,
    "--dg-color-brand-border": colorTokens.brandBorder,
    "--dg-color-primary": colorTokens.brand,
    "--dg-color-link": colorTokens.brand,
    "--dg-color-accent-text": colorTokens.brand,
    "--dg-color-control-primary": colorTokens.textPrimary,
    "--dg-color-control-primary-hover": colorTokens.textSecondary,
    "--dg-color-control-primary-text": colorTokens.textInverse,
    "--dg-color-control-active-bg": colorTokens.surfaceSecondary,
    "--dg-color-control-active-border": colorTokens.border,
    "--dg-color-control-active-text": colorTokens.textPrimary,
    "--dg-color-control-active-hover": colorTokens.borderSubtle,
    "--dg-color-success": colorTokens.success,
    "--dg-color-success-bg": colorTokens.successSoft,
    "--dg-color-success-text": "#166534",
    "--dg-color-success-border": colorTokens.successBorder,
    "--dg-color-warning": colorTokens.warning,
    "--dg-color-warning-bg": colorTokens.warningSoft,
    "--dg-color-warning-text": "#92400E",
    "--dg-color-warning-border": colorTokens.warningBorder,
    "--dg-color-danger": colorTokens.danger,
    "--dg-color-danger-bg": colorTokens.dangerSoft,
    "--dg-color-danger-text": "#B91C1C",
    "--dg-color-danger-border": colorTokens.dangerBorder,
    "--dg-color-danger-dark": "#991B1B",
    "--dg-color-info": colorTokens.brandLight,
    "--dg-color-info-bg": colorTokens.brandSoft,
    "--dg-color-info-text": "#1D4ED8",
    "--dg-color-info-border": colorTokens.brandBorder,
    "--dg-color-dark": colorTokens.textPrimary,
    "--dg-color-dark-elevated": colorTokens.textSecondary,
    "--dg-color-today-bg": colorTokens.brandSoft,
    "--dg-color-today-text": "#1D4ED8",
    "--dg-color-today-border": "#93C5FD",
    "--color-bg": colorTokens.background,
    "--color-surface": colorTokens.surface,
    "--color-bg-secondary": colorTokens.surfaceSecondary,
    "--color-row-alt": colorTokens.surfaceMuted,
    "--color-row-hover": colorTokens.surfaceSecondary,
    "--color-border": colorTokens.border,
    "--color-border-light": colorTokens.borderSubtle,
    "--color-border-focus": colorTokens.brandLight,
    "--color-text-primary": colorTokens.textPrimary,
    "--color-text-secondary": colorTokens.textSecondary,
    "--color-text-muted": colorTokens.textMuted,
    "--color-text-subtle": colorTokens.textSubtle,
    "--color-text-faint": "#718096",
    "--color-text-inverse": colorTokens.textInverse,
    "--color-brand": colorTokens.brand,
    "--color-brand-light": colorTokens.brandLight,
    "--color-brand-bg": colorTokens.brandSoft,
    "--color-brand-border": colorTokens.brandBorder,
    "--color-primary": colorTokens.brand,
    "--color-link": colorTokens.brand,
    "--color-accent-text": colorTokens.brand,
    "--color-control-primary": colorTokens.textPrimary,
    "--color-control-primary-hover": colorTokens.textSecondary,
    "--color-control-primary-text": colorTokens.textInverse,
    "--color-control-active-bg": colorTokens.surfaceSecondary,
    "--color-control-active-border": colorTokens.border,
    "--color-control-active-text": colorTokens.textPrimary,
    "--color-control-active-hover": colorTokens.borderSubtle,
    "--color-success": colorTokens.success,
    "--color-success-bg": colorTokens.successSoft,
    "--color-success-text": "#166534",
    "--color-success-border": colorTokens.successBorder,
    "--color-warning": colorTokens.warning,
    "--color-warning-bg": colorTokens.warningSoft,
    "--color-warning-text": "#92400E",
    "--color-warning-border": colorTokens.warningBorder,
    "--color-danger": colorTokens.danger,
    "--color-danger-bg": colorTokens.dangerSoft,
    "--color-danger-text": "#B91C1C",
    "--color-danger-border": colorTokens.dangerBorder,
    "--color-danger-dark": "#991B1B",
    "--color-info": colorTokens.brandLight,
    "--color-info-bg": colorTokens.brandSoft,
    "--color-info-text": "#1D4ED8",
    "--color-info-border": colorTokens.brandBorder,
    "--color-dark": colorTokens.textPrimary,
    "--color-dark-elevated": colorTokens.textSecondary,
    "--color-today-bg": colorTokens.brandSoft,
    "--color-today-text": "#1D4ED8",
    "--color-today-border": "#93C5FD",
    "--shadow-raised": shadowTokens.raised,
    "--shadow-float": shadowTokens.float,
    "--shadow-menu": shadowTokens.menu,
    "--shadow-modal": shadowTokens.modal,
    "--shadow-panel": shadowTokens.panel,
    "--shadow-drag": shadowTokens.drag,
    "--dg-shadow-sidebar-toggle": "0 1px 4px rgba(0,0,0,0.08)",
    "--dg-shadow-staff-detail": "0 8px 40px rgba(0, 0, 0, 0.16), 0 2px 12px rgba(0, 0, 0, 0.08)",
    "--dg-shadow-auth-card": "0 2px 16px rgba(0, 0, 0, 0.07)",
    "--header-height": webLayoutTokens.headerHeight,
    "--dg-toolbar-h": webLayoutTokens.toolbarHeight,
    "--dg-btn-radius": buttonTokens.radius,
    "--dg-btn-h": buttonTokens.height,
    "--dg-btn-h-sm": buttonTokens.heightSm,
    "--dg-btn-h-xs": buttonTokens.heightXs,
    "--dg-btn-h-lg": buttonTokens.heightLg,
    "--dg-btn-px": buttonTokens.paddingX,
    "--dg-btn-px-sm": buttonTokens.paddingXSm,
    "--dg-btn-px-xs": buttonTokens.paddingXXs,
    "--dg-btn-gap": buttonTokens.gap,
    "--dg-btn-icon": buttonTokens.iconSize,
    "--dg-fs-page-title": typographyTokens.fontSize.pageTitle,
    "--dg-fs-section-title": typographyTokens.fontSize.sectionTitle,
    "--dg-fs-card-title": typographyTokens.fontSize.cardTitle,
    "--dg-fs-heading": typographyTokens.fontSize.heading,
    "--dg-fs-title": typographyTokens.fontSize.title,
    "--dg-fs-body": typographyTokens.fontSize.body,
    "--dg-fs-body-sm": typographyTokens.fontSize.bodySm,
    "--dg-fs-label": typographyTokens.fontSize.label,
    "--dg-fs-caption": typographyTokens.fontSize.caption,
    "--dg-fs-footnote": typographyTokens.fontSize.footnote,
    "--dg-fs-badge": typographyTokens.fontSize.badge,
    "--dg-fs-micro": typographyTokens.fontSize.micro,
    "--dg-space-xs": webSpacingTokens.xs,
    "--dg-space-sm": webSpacingTokens.sm,
    "--dg-space-md": webSpacingTokens.md,
    "--dg-space-lg": webSpacingTokens.lg,
    "--dg-space-xl": webSpacingTokens.xl,
    "--dg-space-2xl": webSpacingTokens["2xl"],
    "--dg-space-3xl": webSpacingTokens["3xl"],
    "--dg-space-4xl": webSpacingTokens["4xl"],
    "--dg-space-5xl": webSpacingTokens["5xl"],
    "--dg-lh-tight": typographyTokens.lineHeight.tight,
    "--dg-lh-normal": typographyTokens.lineHeight.normal,
    "--dg-lh-loose": typographyTokens.lineHeight.loose,
    "--dg-grid-name-col": webLayoutTokens.gridNameColumn,
    "--dg-grid-cell-height": webLayoutTokens.gridCellHeight,
    "--dg-grid-col-min": webLayoutTokens.gridColumnMin,
    "--dg-grid-name-col-tablet": webResponsiveTokens.tablet.gridNameColumn,
    "--dg-grid-col-min-tablet": webResponsiveTokens.tablet.gridColumnMin,
    "--dg-fs-page-title-small-desktop": webResponsiveTokens.smallDesktop.pageTitle,
    "--dg-fs-section-title-small-desktop": webResponsiveTokens.smallDesktop.sectionTitle,
    "--dg-toolbar-h-mobile": webResponsiveTokens.mobile.toolbarHeight,
    "--dg-fs-page-title-mobile": webResponsiveTokens.mobile.pageTitle,
    "--dg-fs-section-title-mobile": webResponsiveTokens.mobile.sectionTitle,
    "--dg-fs-card-title-mobile": webResponsiveTokens.mobile.cardTitle,
    "--dg-fs-heading-mobile": webResponsiveTokens.mobile.heading,
    "--dg-fs-title-mobile": webResponsiveTokens.mobile.title,
    "--dg-fs-badge-mobile": webResponsiveTokens.mobile.badge,
    "--dg-fs-micro-mobile": webResponsiveTokens.mobile.micro,
    "--dg-grid-name-col-mobile": webResponsiveTokens.mobile.gridNameColumn,
    "--tooltip-font-size": "var(--dg-fs-label)",
    "--tooltip-border-radius": "var(--dg-radius-sm)",
    "--tooltip-shadow": shadowTokens.tooltip,
    "--dg-duration-fast": motionTokens.fast,
    "--dg-duration-standard": motionTokens.standard,
    "--dg-radius-sm": webRadiusTokens.sm,
    "--dg-radius-md": webRadiusTokens.md,
    "--dg-radius-lg": webRadiusTokens.lg,
    "--dg-radius-xl": webRadiusTokens.xl,
    "--dg-tab-shell-radius": webRadiusTokens.tabShell,
    "--dg-tab-shell-pad": webRadiusTokens.tabShellPad,
    "--dg-tab-inner-radius": webRadiusTokens.tabInner,
    "--dg-overlay": overlayTokens.background,
    "--dg-overlay-blur": overlayTokens.blur,
    "--dg-focus-ring": stateEffectTokens.focusRing,
    "--dg-danger-ring": stateEffectTokens.dangerRing,
    "--dg-locked-bg": stateEffectTokens.lockedBackground,
    "--dg-on-dark-muted": stateEffectTokens.onDarkMuted,
    "--dg-on-dark-subtle": stateEffectTokens.onDarkSubtle,
    "--dg-on-dark-secondary": stateEffectTokens.onDarkSecondary,
    "--dg-on-dark-description": stateEffectTokens.onDarkDescription,
    "--dg-on-dark-control": stateEffectTokens.onDarkControl,
    "--dg-on-dark-control-hover": stateEffectTokens.onDarkControlHover,
    "--dg-on-dark-control-border": stateEffectTokens.onDarkControlBorder,
    "--dg-toast-success-bg": toastTokens.successBackground,
    "--dg-toast-success-border": toastTokens.successBorder,
    "--dg-toast-error-bg": toastTokens.errorBackground,
    "--dg-toast-error-border": toastTokens.errorBorder,
    "--dg-toast-info-bg": toastTokens.infoBackground,
    "--dg-toast-info-border": toastTokens.infoBorder,
    "--dg-toast-warning-bg": toastTokens.warningBackground,
    "--dg-toast-warning-border": toastTokens.warningBorder,
    "--background": shadcnTokens.background,
    "--foreground": shadcnTokens.foreground,
    "--card": shadcnTokens.card,
    "--card-foreground": shadcnTokens.cardForeground,
    "--popover": shadcnTokens.popover,
    "--popover-foreground": shadcnTokens.popoverForeground,
    "--primary": shadcnTokens.primary,
    "--primary-foreground": shadcnTokens.primaryForeground,
    "--secondary": shadcnTokens.secondary,
    "--secondary-foreground": shadcnTokens.secondaryForeground,
    "--muted": shadcnTokens.muted,
    "--muted-foreground": shadcnTokens.mutedForeground,
    "--accent": shadcnTokens.accent,
    "--accent-foreground": shadcnTokens.accentForeground,
    "--destructive": shadcnTokens.destructive,
    "--border": shadcnTokens.border,
    "--input": shadcnTokens.input,
    "--ring": shadcnTokens.ring,
    "--chart-1": shadcnTokens.chart1,
    "--chart-2": shadcnTokens.chart2,
    "--chart-3": shadcnTokens.chart3,
    "--chart-4": shadcnTokens.chart4,
    "--chart-5": shadcnTokens.chart5,
    "--radius": shadcnTokens.radius,
    "--sidebar": shadcnTokens.sidebar,
    "--sidebar-foreground": shadcnTokens.sidebarForeground,
    "--sidebar-primary": shadcnTokens.sidebarPrimary,
    "--sidebar-primary-foreground": shadcnTokens.sidebarPrimaryForeground,
    "--sidebar-accent": shadcnTokens.sidebarAccent,
    "--sidebar-accent-foreground": shadcnTokens.sidebarAccentForeground,
    "--sidebar-border": shadcnTokens.sidebarBorder,
    "--sidebar-ring": shadcnTokens.sidebarRing,
  };
}
