export const AUTH_RELEASE_ROLES = [
  "public",
  "regular",
  "management",
  "super_admin",
  "gridmaster",
] as const;

export const AUTH_RELEASE_STATES = [
  "unknown_identity",
  "active",
  "inactive",
  "invited",
  "onboarding_complete",
  "suspended",
  "restored",
  "recovery",
  "mfa_disabled",
  "mfa_enabled",
  "stale_session",
  "revoked_session",
  "organization_switch",
] as const;

export const AUTH_RELEASE_BROWSER_ENGINES = ["chromium", "firefox", "webkit"] as const;
export const AUTH_RELEASE_NATIVE_TARGETS = ["android", "ios", "physical_device"] as const;

export type AuthReleaseRole = (typeof AUTH_RELEASE_ROLES)[number];
export type AuthReleaseState = (typeof AUTH_RELEASE_STATES)[number];
export type AuthReleaseBrowserEngine = (typeof AUTH_RELEASE_BROWSER_ENGINES)[number];
export type AuthReleaseNativeTarget = (typeof AUTH_RELEASE_NATIVE_TARGETS)[number];
export type AuthReleaseEvidenceStatus = "automated" | "observed" | "pending" | "unavailable";

export type AuthReleaseMatrixRow = {
  id: string;
  role: AuthReleaseRole;
  state: AuthReleaseState;
  surface: "web" | "native";
  organization: "calmhaven" | "platform";
  expectedAdmission: "allowed" | "blocked" | "challenge" | "limited";
  evidenceOwner: string;
  evidenceStatus: AuthReleaseEvidenceStatus;
  browserEngines?: readonly AuthReleaseBrowserEngine[];
  nativeTargets?: readonly AuthReleaseNativeTarget[];
};

export const AUTH_RELEASE_MATRIX: readonly AuthReleaseMatrixRow[] = [
  {
    id: "public-unknown-identity",
    role: "public",
    state: "unknown_identity",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "blocked",
    evidenceOwner: "e2e/login.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-active",
    role: "regular",
    state: "active",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-inactive",
    role: "regular",
    state: "inactive",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "limited",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-invited",
    role: "regular",
    state: "invited",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "challenge",
    evidenceOwner: "apps/web/src/app/api/invitations/accept/route.test.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "management-active",
    role: "management",
    state: "active",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "super-admin-active",
    role: "super_admin",
    state: "active",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "e2e/login.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "super-admin-onboarding-complete",
    role: "super_admin",
    state: "onboarding_complete",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "gridmaster-platform-entry",
    role: "gridmaster",
    state: "active",
    surface: "web",
    organization: "platform",
    expectedAdmission: "limited",
    evidenceOwner: "apps/web/src/app/api/auth/login/route.test.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-suspended-organization",
    role: "regular",
    state: "suspended",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "blocked",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-restored-organization",
    role: "regular",
    state: "restored",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-recovery",
    role: "regular",
    state: "recovery",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "challenge",
    evidenceOwner: "unit:web-recovery-completion",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "super-admin-mfa-disabled",
    role: "super_admin",
    state: "mfa_disabled",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner:
      "blueprint/history/features/19d2-mfa-assurance-and-sensitive-action-reauthentication.md",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "super-admin-mfa-enabled",
    role: "super_admin",
    state: "mfa_enabled",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "challenge",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-stale-session",
    role: "regular",
    state: "stale_session",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "challenge",
    evidenceOwner: "e2e/auth-release-qualification.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "regular-revoked-session",
    role: "regular",
    state: "revoked_session",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "blocked",
    evidenceOwner: "e2e/auth-session-continuity.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "super-admin-organization-switch",
    role: "super_admin",
    state: "organization_switch",
    surface: "web",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "e2e/auth-session-continuity.spec.ts",
    evidenceStatus: "automated",
    browserEngines: AUTH_RELEASE_BROWSER_ENGINES,
  },
  {
    id: "native-android-super-admin-mfa-enabled",
    role: "super_admin",
    state: "mfa_enabled",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "challenge",
    evidenceOwner: "manual:android-emulator:2026-09-13",
    evidenceStatus: "observed",
    nativeTargets: ["android"],
  },
  {
    id: "native-ios-super-admin-mfa-enabled",
    role: "super_admin",
    state: "mfa_enabled",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "challenge",
    evidenceOwner: "manual:ios-simulator:2026-09-13",
    evidenceStatus: "observed",
    nativeTargets: ["ios"],
  },
  {
    id: "native-physical-super-admin-mfa-enabled",
    role: "super_admin",
    state: "mfa_enabled",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "challenge",
    evidenceOwner: "manual:physical-ios:2026-09-14",
    evidenceStatus: "observed",
    nativeTargets: ["physical_device"],
  },
  {
    id: "native-android-regular-suspension-recovery",
    role: "regular",
    state: "restored",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "manual:android-emulator:2026-09-13",
    evidenceStatus: "observed",
    nativeTargets: ["android"],
  },
  {
    id: "native-ios-regular-suspension-recovery",
    role: "regular",
    state: "restored",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "manual:ios-simulator:2026-09-14",
    evidenceStatus: "observed",
    nativeTargets: ["ios"],
  },
  {
    id: "native-physical-regular-suspension-recovery",
    role: "regular",
    state: "restored",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "manual:physical-ios:2026-09-14",
    evidenceStatus: "observed",
    nativeTargets: ["physical_device"],
  },
  {
    id: "native-android-regular-organization-switch",
    role: "regular",
    state: "organization_switch",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "manual:android-emulator:2026-09-13",
    evidenceStatus: "observed",
    nativeTargets: ["android"],
  },
  {
    id: "native-ios-super-admin-organization-switch",
    role: "super_admin",
    state: "organization_switch",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "manual:ios-simulator:2026-09-13",
    evidenceStatus: "observed",
    nativeTargets: ["ios"],
  },
  {
    id: "native-physical-regular-organization-switch",
    role: "regular",
    state: "organization_switch",
    surface: "native",
    organization: "calmhaven",
    expectedAdmission: "allowed",
    evidenceOwner: "manual:physical-ios:2026-09-14",
    evidenceStatus: "observed",
    nativeTargets: ["physical_device"],
  },
] as const;
